/*
 * Copyright (C) 2013 Universitat Pompeu Fabra
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.gwaspi.constants;

public class cDBOperations {

	public static final String f_ID = "id";
	public static final String f_OP_NAME = "operation_name";
	public static final String f_OP_NETCDF_NAME = "netcdf_name";
	public static final String f_OP_TYPE = "operation_type";
	public static final String f_OP_COMMAND = "operation_command";
	public static final String f_PARENT_MATRIXID = "parent_matrix_id";
	public static final String f_PARENT_OPID = "parent_operation_id";
	public static final String f_DESCRIPTION = "description";
	public static final String f_STUDYID = "studyid";
	public static final String f_CREATION_DATE = "creation_date";
	public static final String T_OPERATIONS = "OPERATIONS";
	public static final String[] T_CREATE_OPERATIONS = new String[] {
		f_ID + " INTEGER generated by default as identity",
		f_PARENT_MATRIXID + " INTEGER",
		f_PARENT_OPID + " INTEGER",
		f_OP_NAME + " VARCHAR(255) NOT NULL",
		f_OP_NETCDF_NAME + " VARCHAR(255) NOT NULL",
		f_OP_TYPE + " VARCHAR(32)",
		f_OP_COMMAND + " VARCHAR(255)",
		f_DESCRIPTION + " VARCHAR(2000)",
		f_STUDYID + " INTEGER",
		f_CREATION_DATE + " TIMESTAMP default CURRENT_TIMESTAMP"
	};
	public static final String[] F_INSERT_OPERATION = new String[] {
		f_PARENT_MATRIXID,
		f_PARENT_OPID,
		f_OP_NAME,
		f_OP_NETCDF_NAME,
		f_OP_TYPE,
		f_OP_COMMAND,
		f_DESCRIPTION,
		f_STUDYID
	};
}
