/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

package org.gwaspi.constants;

/**
 *
 * @author Fernando Muñiz Fernandez
 * IBE, Institute of Evolutionary Biology (UPF-CSIC)
 * CEXS-UPF-PRBB
 */
public class cDBReports {
    
    public static String f_ID = "id";
    public static String f_RP_NAME = "report_name";
    public static String f_DESCRIPTION = "description";
    public static String f_RP_FILE_NAME = "file_name";
    public static String f_RP_TYPE = "report_type";
    public static String f_PARENT_MATRIXID = "parent_matrix_id";
    public static String f_PARENT_OPID = "parent_operation_id";
    public static String f_STUDYID = "studyid";
    public static String f_CREATION_DATE="creation_date";

    public static String T_REPORTS = "REPORTS";
    public static String[] T_CREATE_REPORTS = new String[]{f_ID+" INTEGER generated by default as identity",
                                                        f_RP_NAME+" VARCHAR(255) NOT NULL",
                                                        f_DESCRIPTION+" LONG VARCHAR",
                                                        f_RP_FILE_NAME+" VARCHAR(255) NOT NULL",
                                                        f_RP_TYPE+" VARCHAR(32)",
                                                        f_PARENT_MATRIXID+" INTEGER",
                                                        f_PARENT_OPID+" INTEGER",
                                                        f_STUDYID+" INTEGER",
                                                        f_CREATION_DATE+" TIMESTAMP default CURRENT_TIMESTAMP"
                                                        };
    public static final String[] F_INSERT_REPORT = new String[]{f_RP_NAME,
                                                        f_DESCRIPTION,
                                                        f_RP_FILE_NAME,
                                                        f_RP_TYPE,
                                                        f_PARENT_MATRIXID,
                                                        f_PARENT_OPID,
                                                        f_STUDYID,
                                                        };

}
