/*
 * Copyright (C) 2013 Universitat Pompeu Fabra
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.gwaspi.constants;

public class cDBReports {

	public static final String f_ID = "id";
	public static final String f_RP_NAME = "report_name";
	public static final String f_DESCRIPTION = "description";
	public static final String f_RP_FILE_NAME = "file_name";
	public static final String f_RP_TYPE = "report_type";
	public static final String f_PARENT_MATRIXID = "parent_matrix_id";
	public static final String f_PARENT_OPID = "parent_operation_id";
	public static final String f_STUDYID = "studyid";
	public static final String f_CREATION_DATE = "creation_date";
	public static final String T_REPORTS = "REPORTS";
	public static final String[] T_CREATE_REPORTS = new String[] {
		f_ID + " INTEGER generated by default as identity",
		f_RP_NAME + " VARCHAR(255) NOT NULL",
		f_DESCRIPTION + " LONG VARCHAR",
		f_RP_FILE_NAME + " VARCHAR(255) NOT NULL",
		f_RP_TYPE + " VARCHAR(32)",
		f_PARENT_MATRIXID + " INTEGER",
		f_PARENT_OPID + " INTEGER",
		f_STUDYID + " INTEGER",
		f_CREATION_DATE + " TIMESTAMP default CURRENT_TIMESTAMP"
	};
	public static final String[] F_INSERT_REPORT = new String[] {
		f_RP_NAME,
		f_DESCRIPTION,
		f_RP_FILE_NAME,
		f_RP_TYPE,
		f_PARENT_MATRIXID,
		f_PARENT_OPID,
		f_STUDYID
	};

	private cDBReports() {
	}
}
