#!/bin/bash
# Runs COMBI unit tests

export MAVEN_OPTS="-Xms1024M -Xmx2048M"
time (mvn test -DargLine="${MAVEN_OPTS}" -Dtest=TestAssociationTestScripts#testCombiPermutationBig > z 2> z2)
xmessage -center "COMBI tests are done (on localhost)!"

