package org.gwaspi.model;

import java.io.IOException;
import org.gwaspi.netCDF.matrices.MatrixMetadata;

/**
 *
 * @author Fernando Muñiz Fernandez
 * IBE, Institute of Evolutionary Biology (UPF-CSIC)
 * CEXS-UPF-PRBB
 */
public class Matrix {

	private int matrixId; // id INTEGER generated by default as identity
	private int studyId; // studyId INTEGER
	private MatrixMetadata matrixMetadata;

//	public Matrix() {
//
//		this.matrixId = Integer.MIN_VALUE;
//		this.studyId = Integer.MIN_VALUE;
//		this.matrixMetadata = null;
//	}

	public Matrix(int matrixId, int studyId, MatrixMetadata matrixMetadata) {

		this.matrixId = matrixId;
		this.studyId = studyId;
		this.matrixMetadata = matrixMetadata;
	}

	public int getId() {
		return matrixId;
	}

	public int getStudyId() {
		return studyId;
	}

	public MatrixMetadata getMatrixMetadata() {
		return matrixMetadata;
	}
}
