package org.gwaspi.model;

import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;

/**
 *
 * @author Fernando Muñiz Fernandez
 * IBE, Institute of Evolutionary Biology (UPF-CSIC)
 * CEXS-UPF-PRBB
 */
@Entity
@Table(name = "matrix")
@NamedQueries({
	@NamedQuery(
		name = "matrix_fetchById",
		query = "SELECT m FROM Matrix m WHERE m.id = :id"),
	@NamedQuery(
		name = "matrix_listByStudyId",
		query = "SELECT m FROM Matrix m WHERE m.studyId = :studyId"),
})
public class Matrix implements Serializable {

	private int matrixId; // id INTEGER generated by default as identity
	private int studyId; // studyId INTEGER
	private MatrixMetadata matrixMetadata;

	protected Matrix() {

		this.matrixId = Integer.MIN_VALUE;
		this.studyId = Integer.MIN_VALUE;
		this.matrixMetadata = null;
	}

	public Matrix(int matrixId, int studyId, MatrixMetadata matrixMetadata) {

		this.matrixId = matrixId;
		this.studyId = studyId;
		this.matrixMetadata = matrixMetadata;
	}

	@Id
	@Column(
		name       = "id",
		unique     = false,
		nullable   = false,
		insertable = true,
		updatable  = false
		)
	public int getId() {
		return matrixId;
	}

	@Id
	@Column(
		name       = "studyId",
		unique     = false,
		nullable   = false,
		insertable = true,
		updatable  = false
		)
	public int getStudyId() {
		return studyId;
	}

	@Column(
		name       = "matrixMetadata",
		unique     = false,
		nullable   = false,
		insertable = true,
		updatable  = false
		)
	public MatrixMetadata getMatrixMetadata() {
		return matrixMetadata;
	}
}
