package org.gwaspi.model;

/**
 *
 * @author Fernando Muñiz Fernandez
 * IBE, Institute of Evolutionary Biology (UPF-CSIC)
 * CEXS-UPF-PRBB
 */
public class Operation {

	private int id; // INTEGER generated by default as identity
	private String friendlyName; // VARCHAR(255) NOT NULL
	private String netCDFName; // VARCHAR(255) NOT NULL
	private String type; // VARCHAR(32) NOT NULL
	private int parentMatrixId; // INTEGER
	private int parentOperationId; // INTEGER
	private String command; // VARCHAR(2000)
	private String description; // VARCHAR(255)
	private int studyId; // INTEGER

//	public Operation() {
//
//		this.id = Integer.MIN_VALUE;
//		this.friendlyName = "";
//		this.netCDFName = "";
//		this.type = "";
//		this.parentMatrixId = Integer.MIN_VALUE;
//		this.parentOperationId = Integer.MIN_VALUE;
//		this.command = "";
//		this.description = "";
//		this.studyId = Integer.MIN_VALUE;
//	}

	public Operation(
			int id,
			String friendlyName,
			String netCDFName,
			String type,
			int parentMatrixId,
			int parentOperationId,
			String command,
			String description,
			int studyId)
	{
		this.id = id;
		this.friendlyName = friendlyName;
		this.netCDFName = netCDFName;
		this.type = type;
		this.parentMatrixId = parentMatrixId;
		this.parentOperationId = parentOperationId;
		this.command = command;
		this.description = description;
		this.studyId = studyId;
	}

	public int getId() {
		return id;
	}

	public int getParentMatrixId() {
		return parentMatrixId;
	}

	public int getStudyId() {
		return studyId;
	}

	public String getFriendlyName() {
		return friendlyName;
	}

	public String getNetCDFName() {
		return netCDFName;
	}

	public String getOperationType() {
		return type;
	}

	public String getCommand() {
		return command;
	}

	public String getDescription() {
		return description;
	}

	public int getParentOperationId() {
		return parentOperationId;
	}
}
