package org.gwaspi.model;

import org.gwaspi.constants.cDBGWASpi;
import org.gwaspi.constants.cDBReports;
import org.gwaspi.database.DbManager;
import org.gwaspi.global.ServiceLocator;
import java.io.IOException;
import java.util.List;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Fernando Muñiz Fernandez
 * IBE, Institute of Evolutionary Biology (UPF-CSIC)
 * CEXS-UPF-PRBB
 */
public class Report {

	private static final Logger log
			= LoggerFactory.getLogger(Report.class);

	private int id = Integer.MIN_VALUE; // INTEGER generated by default as identity
	private String friendlyName = ""; // VARCHAR(255) NOT NULL
	private String fileName = ""; // VARCHAR(255) NOT NULL
	private String type = ""; // VARCHAR(32) NOT NULL
	private int parentMatrixId = Integer.MIN_VALUE; // INTEGER
	private int parentOpId = Integer.MIN_VALUE; // INTEGER
	private String description = ""; // VARCHAR(255)
	private int studyId = Integer.MIN_VALUE; // INTEGER

	/**
	 * This will init the Matrix object requested from the DB
	 */
	public Report(int _reportId) throws IOException {
		List<Map<String, Object>> rs = getReportMetadata(_reportId);
		id = _reportId;

		// PREVENT PHANTOM-DB READS EXCEPTIONS
		if (!rs.isEmpty() && rs.get(0).size() == cDBReports.T_CREATE_REPORTS.length) {
			friendlyName = (rs.get(0).get(cDBReports.f_RP_NAME) != null) ? rs.get(0).get(cDBReports.f_RP_NAME).toString() : "";
			fileName = (rs.get(0).get(cDBReports.f_RP_FILE_NAME) != null) ? rs.get(0).get(cDBReports.f_RP_FILE_NAME).toString() : "";
			type = (rs.get(0).get(cDBReports.f_RP_TYPE) != null) ? rs.get(0).get(cDBReports.f_RP_TYPE).toString() : "";
			parentMatrixId = (rs.get(0).get(cDBReports.f_PARENT_MATRIXID) != null) ? Integer.parseInt(rs.get(0).get(cDBReports.f_PARENT_MATRIXID).toString()) : -1;
			parentOpId = (rs.get(0).get(cDBReports.f_PARENT_OPID) != null) ? Integer.parseInt(rs.get(0).get(cDBReports.f_PARENT_OPID).toString()) : -1;
			description = (rs.get(0).get(cDBReports.f_DESCRIPTION) != null) ? rs.get(0).get(cDBReports.f_DESCRIPTION).toString() : "";
			studyId = (rs.get(0).get(cDBReports.f_STUDYID) != null) ? Integer.parseInt(rs.get(0).get(cDBReports.f_STUDYID).toString()) : 0;
		}
	}

	public int getId() {
		return id;
	}

	public int getParentMatrixId() {
		return parentMatrixId;
	}

	public int getStudyId() {
		return studyId;
	}

	public String getFriendlyName() {
		return friendlyName;
	}

	public String getFileName() {
		return fileName;
	}

	public String getReportType() {
		return type;
	}

	public int getParentOperationId() {
		return parentOpId;
	}

	public String getDescription() {
		return description;
	}

	private static List<Map<String, Object>> getReportMetadata(int rpId) throws IOException {
		List<Map<String, Object>> rs = null;
		String dbName = cDBGWASpi.DB_DATACENTER;
		DbManager studyDbManager = ServiceLocator.getDbManager(dbName);
		try {
			rs = studyDbManager.executeSelectStatement("SELECT * FROM " + cDBGWASpi.SCH_MATRICES + "." + cDBReports.T_REPORTS + " WHERE " + cDBReports.f_ID + "=" + rpId + "  WITH RR");
		} catch (Exception ex) {
			log.error(null, ex);
		}

		return rs;
	}
}
