package org.gwaspi.model;

import java.util.Date;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 *
 * @author Fernando Muñiz Fernandez
 * IBE, Institute of Evolutionary Biology (UPF-CSIC)
 * CEXS-UPF-PRBB
 */
public class Study {

	private static final Logger log
			= LoggerFactory.getLogger(Study.class);

	private int id = Integer.MIN_VALUE; // id INTEGER generated by default as identity
	private String name = ""; // name VARCHAR(64)
	private String description = ""; // study_description LONG VARCHAR
	private String studyType = ""; // study_type VARCHAR(255)
	private String validity = ""; // validity SMALLINT
	private Date creationDate; // creation_date TIMESTAMP (2009-05-13 17:22:10.984)
//	private List<Integer> studyMatrices = new ArrayList<Integer>();

//	public Study() {
//
//		this.id = Integer.MIN_VALUE;
//		this.name = "";
//		this.description = "";
//		this.studyType = "";
//		this.validity = "";
//		this.creationDate = new Date();
////		this.studyMatrices = new ArrayList<Integer>();
//	}

	public Study(int id, String name, String description, String studyType, String validity, Date creationDate) {

		this.id = id;
		this.name = name;
		this.description = description;
		this.studyType = studyType;
		this.validity = validity;
		this.creationDate = (Date) creationDate.clone();
//		this.studyMatrices = new ArrayList<Integer>();
	}

	public int getId() {
		return id;
	}

	public String getName() {
		return name;
	}

	public String getDescription() {
		return description;
	}

	public String getStudyType() {
		return studyType;
	}

	public String getValidity() {
		return validity;
	}

	public Date getCreationDate() {
		return creationDate;
	}
}
