package model;

/**
 *
 * @author Fernando Muñiz Fernandez
 * IBE, Institute of Evolutionary Biology (UPF-CSIC)
 * CEXS-UPF-PRBB
 */

import java.io.IOException;
import netCDF.matrices.MatrixMetadata;

public class Matrix {

    private int matrixId = Integer.MIN_VALUE;     //id INTEGER generated by default as identity
    private int studyId = Integer.MIN_VALUE;    //studyId INTEGER

    public MatrixMetadata matrixMetadata;


    //This will init the Matrix object requested from the DB
    public Matrix(int _matrixId) throws IOException{

        matrixId = _matrixId;
        matrixMetadata = new MatrixMetadata(_matrixId);
        studyId = matrixMetadata.getStudyId();
    }


    public int getMatrixId(){
        return matrixId;
    }

    public int getStudyId(){
        return studyId;
    }


    public MatrixMetadata getMatrixMetadata() throws IOException{
        return matrixMetadata;
    }
}
