package org.gwaspi.gui;

/**
 *
 * @author u56124
 */
public class ChartManagerTab extends javax.swing.JFrame {

	/**
	 * Creates new form LogTab
	 */
	public ChartManagerTab() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panel_ChartTab = new javax.swing.JPanel();
        labe_SelectPlot = new javax.swing.JLabel();
        combo_SelectPlot = new javax.swing.JComboBox();
        label_ReportFile = new javax.swing.JLabel();
        textField_ReportFile = new javax.swing.JTextField();
        button_ReportFile = new javax.swing.JButton();
        button_SaveCompleteChart = new javax.swing.JButton();
        button_SaveZoomedChart = new javax.swing.JButton();
        panel_Plot = new javax.swing.JPanel();
        
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        
        labe_SelectPlot.setText("Select Plot type:");
        
        combo_SelectPlot.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-log(p) vs position", "Chi² Q/Q plot" }));
        
        label_ReportFile.setText("Report File:");
        
        textField_ReportFile.setMinimumSize(new java.awt.Dimension(10, 29));
        
        button_ReportFile.setText("Browse");
        
        button_SaveCompleteChart.setText("Save Complete Chart");
        button_SaveCompleteChart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_SaveCompleteChartActionPerformed(evt);
            }
        });
        
        button_SaveZoomedChart.setText("Save Zoomed Chart");
        
        javax.swing.GroupLayout panel_PlotLayout = new javax.swing.GroupLayout(panel_Plot);
        panel_Plot.setLayout(panel_PlotLayout);
        panel_PlotLayout.setHorizontalGroup(
                panel_PlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 866, Short.MAX_VALUE)
                );
        panel_PlotLayout.setVerticalGroup(
                panel_PlotLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGap(0, 401, Short.MAX_VALUE)
                );
        
        javax.swing.GroupLayout panel_ChartTabLayout = new javax.swing.GroupLayout(panel_ChartTab);
        panel_ChartTab.setLayout(panel_ChartTabLayout);
        panel_ChartTabLayout.setHorizontalGroup(
                panel_ChartTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_ChartTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ChartTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ChartTabLayout.createSequentialGroup()
                .addGroup(panel_ChartTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panel_Plot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panel_ChartTabLayout.createSequentialGroup()
                .addGroup(panel_ChartTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(labe_SelectPlot)
                .addComponent(label_ReportFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_ChartTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panel_ChartTabLayout.createSequentialGroup()
                .addComponent(textField_ReportFile, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(button_ReportFile))
                .addComponent(combo_SelectPlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ChartTabLayout.createSequentialGroup()
                .addComponent(button_SaveZoomedChart)
                .addGap(18, 18, 18)
                .addComponent(button_SaveCompleteChart)
                .addGap(12, 12, 12))))
                );
        panel_ChartTabLayout.setVerticalGroup(
                panel_ChartTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_ChartTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_ChartTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(labe_SelectPlot)
                .addComponent(combo_SelectPlot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_ChartTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(button_ReportFile)
                .addComponent(label_ReportFile)
                .addComponent(textField_ReportFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panel_Plot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(panel_ChartTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(button_SaveCompleteChart)
                .addComponent(button_SaveZoomedChart))
                .addContainerGap())
                );
        
        jTabbedPane1.addTab("Charts & Graphics", panel_ChartTab);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 898, Short.MAX_VALUE)
                .addContainerGap())
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 589, Short.MAX_VALUE)
                .addContainerGap())
                );
        
        pack();
    }//GEN-END:initComponents

private void button_SaveCompleteChartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_SaveCompleteChartActionPerformed
}//GEN-LAST:event_button_SaveCompleteChartActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new ChartManagerTab().setVisible(true);
			}
		});
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_ReportFile;
    private javax.swing.JButton button_SaveCompleteChart;
    private javax.swing.JButton button_SaveZoomedChart;
    private javax.swing.JComboBox combo_SelectPlot;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labe_SelectPlot;
    private javax.swing.JLabel label_ReportFile;
    private javax.swing.JPanel panel_ChartTab;
    private javax.swing.JPanel panel_Plot;
    private javax.swing.JTextField textField_ReportFile;
    // End of variables declaration//GEN-END:variables
}
