/*
 * Copyright (C) 2013 Universitat Pompeu Fabra
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.gwaspi.gui;

public class ManhattanPlotNavigator extends javax.swing.JPanel {

	/**
	 * Creates new form ManhattanPlotNavigator
	 */
	public ManhattanPlotNavigator() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        pnl_ChartNavigator = new javax.swing.JPanel();
        pnl_Chart = new javax.swing.JPanel();
        scrl_Chart = new javax.swing.JScrollPane();
        pnl_Footer = new javax.swing.JPanel();
        btn_Back = new javax.swing.JButton();
        pnl_FooterGroup1 = new javax.swing.JPanel();
        btn_Save = new javax.swing.JButton();
        btn_Reset = new javax.swing.JButton();
        btn_Back2 = new javax.swing.JButton();
        pnl_Tracker = new javax.swing.JPanel();
        slid_Tracker = new javax.swing.JSlider();
        pnl_SearchDB = new javax.swing.JPanel();
        cmb_SearchDB = new javax.swing.JComboBox();

        pnl_ChartNavigator.setBorder(javax.swing.BorderFactory.createTitledBorder("Manhattan Plot Navigator"));

        pnl_Chart.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_ChartLayout = new javax.swing.GroupLayout(pnl_Chart);
        pnl_Chart.setLayout(pnl_ChartLayout);
        pnl_ChartLayout.setHorizontalGroup(
                pnl_ChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrl_Chart, javax.swing.GroupLayout.DEFAULT_SIZE, 895, Short.MAX_VALUE)
                );
        pnl_ChartLayout.setVerticalGroup(
                pnl_ChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrl_Chart, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
                );

        javax.swing.GroupLayout pnl_ChartNavigatorLayout = new javax.swing.GroupLayout(pnl_ChartNavigator);
        pnl_ChartNavigator.setLayout(pnl_ChartNavigatorLayout);
        pnl_ChartNavigatorLayout.setHorizontalGroup(
                pnl_ChartNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_ChartNavigatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
                );
        pnl_ChartNavigatorLayout.setVerticalGroup(
                pnl_ChartNavigatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_ChartNavigatorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Chart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
                );

        btn_Back.setText("Back to Table");

        btn_Save.setText("Save View");

        btn_Reset.setText("Reset");

        javax.swing.GroupLayout pnl_FooterGroup1Layout = new javax.swing.GroupLayout(pnl_FooterGroup1);
        pnl_FooterGroup1.setLayout(pnl_FooterGroup1Layout);
        pnl_FooterGroup1Layout.setHorizontalGroup(
                pnl_FooterGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_FooterGroup1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Reset, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_Save, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
                );


        pnl_FooterGroup1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_Reset, btn_Save});

        pnl_FooterGroup1Layout.setVerticalGroup(
                pnl_FooterGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_FooterGroup1Layout.createSequentialGroup()
                .addGroup(pnl_FooterGroup1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_Save)
                .addComponent(btn_Reset))
                .addContainerGap(16, Short.MAX_VALUE))
                );


        pnl_FooterGroup1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btn_Reset, btn_Save});


        btn_Back2.setText("Back to Manhattan Plot");

        javax.swing.GroupLayout pnl_FooterLayout = new javax.swing.GroupLayout(pnl_Footer);
        pnl_Footer.setLayout(pnl_FooterLayout);
        pnl_FooterLayout.setHorizontalGroup(
                pnl_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_Back)
                .addGap(18, 18, 18)
                .addComponent(btn_Back2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 368, Short.MAX_VALUE)
                .addComponent(pnl_FooterGroup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
                );
        pnl_FooterLayout.setVerticalGroup(
                pnl_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_FooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_FooterLayout.createSequentialGroup()
                .addGroup(pnl_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_Back)
                .addComponent(btn_Back2))
                .addGap(71, 71, 71))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_FooterLayout.createSequentialGroup()
                .addComponent(pnl_FooterGroup1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))))
                );

        pnl_Tracker.setBorder(javax.swing.BorderFactory.createTitledBorder("Position"));

        slid_Tracker.setMaximum(17000);
        slid_Tracker.setValue(3500);
        slid_Tracker.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                slid_TrackerMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout pnl_TrackerLayout = new javax.swing.GroupLayout(pnl_Tracker);
        pnl_Tracker.setLayout(pnl_TrackerLayout);
        pnl_TrackerLayout.setHorizontalGroup(
                pnl_TrackerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_TrackerLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(slid_Tracker, javax.swing.GroupLayout.DEFAULT_SIZE, 814, Short.MAX_VALUE)
                .addContainerGap())
                );
        pnl_TrackerLayout.setVerticalGroup(
                pnl_TrackerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(slid_Tracker, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                );

        pnl_SearchDB.setBorder(javax.swing.BorderFactory.createTitledBorder("Search Database"));

        cmb_SearchDB.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout pnl_SearchDBLayout = new javax.swing.GroupLayout(pnl_SearchDB);
        pnl_SearchDB.setLayout(pnl_SearchDBLayout);
        pnl_SearchDBLayout.setHorizontalGroup(
                pnl_SearchDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_SearchDBLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cmb_SearchDB, 0, 614, Short.MAX_VALUE)
                .addContainerGap())
                );
        pnl_SearchDBLayout.setVerticalGroup(
                pnl_SearchDBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_SearchDBLayout.createSequentialGroup()
                .addComponent(cmb_SearchDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
                );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(pnl_SearchDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(pnl_Tracker, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_ChartNavigator, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_Footer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addComponent(pnl_ChartNavigator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Tracker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(pnl_SearchDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnl_Footer, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
                );
    }//GEN-END:initComponents

    private void slid_TrackerMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_slid_TrackerMouseReleased
		// TODO add your handling code here:
    }//GEN-LAST:event_slid_TrackerMouseReleased
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Back2;
    private javax.swing.JButton btn_Reset;
    private javax.swing.JButton btn_Save;
    private javax.swing.JComboBox cmb_SearchDB;
    private javax.swing.JPanel pnl_Chart;
    private javax.swing.JPanel pnl_ChartNavigator;
    private javax.swing.JPanel pnl_Footer;
    private javax.swing.JPanel pnl_FooterGroup1;
    private javax.swing.JPanel pnl_SearchDB;
    private javax.swing.JPanel pnl_Tracker;
    private javax.swing.JScrollPane scrl_Chart;
    private javax.swing.JSlider slid_Tracker;
    // End of variables declaration//GEN-END:variables
}
