/*
 * TestJPanel.java
 *
 * Created on Nov 11, 2009, 12:13:59 PM
 */
package org.gwaspi.gui;

/**
 *
 * @author fernando
 */
public class MatrixExtractPanel extends javax.swing.JPanel {

	/**
	 * Creates new form TestJPanel
	 */
	public MatrixExtractPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents
        
        pnl_NameAndDesc = new javax.swing.JPanel();
        lbl_ParentMatrix = new javax.swing.JLabel();
        lbl_ParentMatrixName = new javax.swing.JLabel();
        lbl_NewMatrixName = new javax.swing.JLabel();
        txt_NewMatrixName = new javax.swing.JTextField();
        scrl_NewMatrixDescription = new javax.swing.JScrollPane();
        txtA_NewMatrixDescription = new javax.swing.JTextArea();
        pnl_MarkerZone = new javax.swing.JPanel();
        lbl_MarkersVariable = new javax.swing.JLabel();
        cmb_MarkersVariable = new javax.swing.JComboBox();
        lbl_MarkersCriteria = new javax.swing.JLabel();
        scrl_MarkersCriteria = new javax.swing.JScrollPane();
        txtA_MarkersCriteria = new javax.swing.JTextArea();
        lbl_MarkersCriteriaFile = new javax.swing.JLabel();
        txt_MarkersCriteriaFile = new javax.swing.JTextField();
        btn_MarkersCriteriaBrowse = new javax.swing.JButton();
        pnl_SampleZone = new javax.swing.JPanel();
        lbl_SamplesVariable = new javax.swing.JLabel();
        cmb_SamplesVariable = new javax.swing.JComboBox();
        lbl_SamplesCriteria = new javax.swing.JLabel();
        scrl_SamplesCriteria = new javax.swing.JScrollPane();
        txtA_SamplesCriteria = new javax.swing.JTextArea();
        lbl_SamplesCriteriaFile = new javax.swing.JLabel();
        txt_SamplesCriteriaFile = new javax.swing.JTextField();
        btn_SamplesCriteriaBrowse = new javax.swing.JButton();
        pnl_Footer = new javax.swing.JPanel();
        btn_Back = new javax.swing.JButton();
        btn_Go = new javax.swing.JButton();
        btn_Help = new javax.swing.JButton();
        
        pnl_NameAndDesc.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Extracted Matrix Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 13))); // NOI18N
        
        lbl_ParentMatrix.setText("Parent Matrix: ");
        
        lbl_ParentMatrixName.setText(" ");
        
        lbl_NewMatrixName.setText("New Matrix Name:");
        
        txt_NewMatrixName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NewMatrixNameActionPerformed(evt);
            }
        });
        
        txtA_NewMatrixDescription.setColumns(20);
        txtA_NewMatrixDescription.setLineWrap(true);
        txtA_NewMatrixDescription.setRows(5);
        txtA_NewMatrixDescription.setBorder(javax.swing.BorderFactory.createTitledBorder("Description"));
        scrl_NewMatrixDescription.setViewportView(txtA_NewMatrixDescription);
        
        javax.swing.GroupLayout pnl_NameAndDescLayout = new javax.swing.GroupLayout(pnl_NameAndDesc);
        pnl_NameAndDesc.setLayout(pnl_NameAndDescLayout);
        pnl_NameAndDescLayout.setHorizontalGroup(
                pnl_NameAndDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_NameAndDescLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_NameAndDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(scrl_NewMatrixDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 688, Short.MAX_VALUE)
                .addGroup(pnl_NameAndDescLayout.createSequentialGroup()
                .addComponent(lbl_NewMatrixName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_NewMatrixName, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE))
                .addGroup(pnl_NameAndDescLayout.createSequentialGroup()
                .addComponent(lbl_ParentMatrix)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_ParentMatrixName)))
                .addContainerGap())
                );
        pnl_NameAndDescLayout.setVerticalGroup(
                pnl_NameAndDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_NameAndDescLayout.createSequentialGroup()
                .addGroup(pnl_NameAndDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_ParentMatrix)
                .addComponent(lbl_ParentMatrixName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_NameAndDescLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_NewMatrixName)
                .addComponent(txt_NewMatrixName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrl_NewMatrixDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        
        pnl_MarkerZone.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Marker Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 13))); // NOI18N
        
        lbl_MarkersVariable.setText("Property / Variable: ");
        
        cmb_MarkersVariable.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        
        lbl_MarkersCriteria.setText("Criteria:");
        
        txtA_MarkersCriteria.setColumns(20);
        txtA_MarkersCriteria.setLineWrap(true);
        txtA_MarkersCriteria.setRows(5);
        scrl_MarkersCriteria.setViewportView(txtA_MarkersCriteria);
        
        lbl_MarkersCriteriaFile.setText("Criteria File:");
        
        btn_MarkersCriteriaBrowse.setText("Browse");
        btn_MarkersCriteriaBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_MarkersCriteriaBrowseActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout pnl_MarkerZoneLayout = new javax.swing.GroupLayout(pnl_MarkerZone);
        pnl_MarkerZone.setLayout(pnl_MarkerZoneLayout);
        pnl_MarkerZoneLayout.setHorizontalGroup(
                pnl_MarkerZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_MarkerZoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_MarkerZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_MarkersCriteriaFile)
                .addComponent(lbl_MarkersCriteria)
                .addComponent(lbl_MarkersVariable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_MarkerZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cmb_MarkersVariable, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(scrl_MarkersCriteria, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addComponent(txt_MarkersCriteriaFile, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_MarkersCriteriaBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
                );
        
        
        pnl_MarkerZoneLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmb_MarkersVariable, scrl_MarkersCriteria, txt_MarkersCriteriaFile});
        
        pnl_MarkerZoneLayout.setVerticalGroup(
                pnl_MarkerZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_MarkerZoneLayout.createSequentialGroup()
                .addGroup(pnl_MarkerZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_MarkersVariable)
                .addComponent(cmb_MarkersVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_MarkerZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_MarkersCriteria)
                .addComponent(scrl_MarkersCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_MarkerZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_MarkersCriteriaFile)
                .addComponent(txt_MarkersCriteriaFile)
                .addComponent(btn_MarkersCriteriaBrowse))
                .addContainerGap())
                );
        
        pnl_SampleZone.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Sample Selection", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("DejaVu Sans", 1, 13))); // NOI18N
        
        lbl_SamplesVariable.setText("Property / Variable: ");
        
        cmb_SamplesVariable.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        
        lbl_SamplesCriteria.setText("Criteria:");
        
        txtA_SamplesCriteria.setColumns(20);
        txtA_SamplesCriteria.setLineWrap(true);
        txtA_SamplesCriteria.setRows(5);
        scrl_SamplesCriteria.setViewportView(txtA_SamplesCriteria);
        
        lbl_SamplesCriteriaFile.setText("Criteria File:");
        
        btn_SamplesCriteriaBrowse.setText("Browse");
        btn_SamplesCriteriaBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SamplesCriteriaBrowseActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout pnl_SampleZoneLayout = new javax.swing.GroupLayout(pnl_SampleZone);
        pnl_SampleZone.setLayout(pnl_SampleZoneLayout);
        pnl_SampleZoneLayout.setHorizontalGroup(
                pnl_SampleZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_SampleZoneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_SampleZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_SamplesVariable)
                .addComponent(lbl_SamplesCriteria)
                .addComponent(lbl_SamplesCriteriaFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_SampleZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(cmb_SamplesVariable, 0, 461, Short.MAX_VALUE)
                .addComponent(scrl_SamplesCriteria, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
                .addComponent(txt_SamplesCriteriaFile, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_SamplesCriteriaBrowse, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
                );
        
        
        pnl_SampleZoneLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cmb_SamplesVariable, scrl_SamplesCriteria, txt_SamplesCriteriaFile});
        
        pnl_SampleZoneLayout.setVerticalGroup(
                pnl_SampleZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_SampleZoneLayout.createSequentialGroup()
                .addGroup(pnl_SampleZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbl_SamplesVariable)
                .addComponent(cmb_SamplesVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_SampleZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(lbl_SamplesCriteria)
                .addComponent(scrl_SamplesCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnl_SampleZoneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(txt_SamplesCriteriaFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_SamplesCriteriaBrowse)
                .addComponent(lbl_SamplesCriteriaFile))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );
        
        btn_Back.setText("Back");
        
        btn_Go.setText("Go!");
        btn_Go.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_GoActionPerformed(evt);
            }
        });
        
        btn_Help.setText("Help");
        btn_Help.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_HelpActionPerformed(evt);
            }
        });
        
        javax.swing.GroupLayout pnl_FooterLayout = new javax.swing.GroupLayout(pnl_Footer);
        pnl_Footer.setLayout(pnl_FooterLayout);
        pnl_FooterLayout.setHorizontalGroup(
                pnl_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_FooterLayout.createSequentialGroup()
                .addComponent(btn_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_Help, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 331, Short.MAX_VALUE)
                .addComponent(btn_Go, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
                );
        pnl_FooterLayout.setVerticalGroup(
                pnl_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnl_FooterLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(pnl_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btn_Go, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btn_Back)
                .addComponent(btn_Help)))
                );
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(pnl_NameAndDesc, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_MarkerZone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnl_SampleZone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addComponent(pnl_Footer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(45, 45, 45)))
                .addContainerGap())
                );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_NameAndDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_MarkerZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_SampleZone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_Footer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
                );
    }//GEN-END:initComponents

    private void btn_MarkersCriteriaBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_MarkersCriteriaBrowseActionPerformed
		// TODO add your handling code here:
}//GEN-LAST:event_btn_MarkersCriteriaBrowseActionPerformed

    private void btn_SamplesCriteriaBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SamplesCriteriaBrowseActionPerformed
		// TODO add your handling code here:
}//GEN-LAST:event_btn_SamplesCriteriaBrowseActionPerformed

    private void btn_GoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_GoActionPerformed
		// TODO add your handling code here:
}//GEN-LAST:event_btn_GoActionPerformed

    private void txt_NewMatrixNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NewMatrixNameActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_txt_NewMatrixNameActionPerformed

    private void btn_HelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_HelpActionPerformed
		// TODO add your handling code here:
}//GEN-LAST:event_btn_HelpActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Back;
    private javax.swing.JButton btn_Go;
    private javax.swing.JButton btn_Help;
    private javax.swing.JButton btn_MarkersCriteriaBrowse;
    private javax.swing.JButton btn_SamplesCriteriaBrowse;
    private javax.swing.JComboBox cmb_MarkersVariable;
    private javax.swing.JComboBox cmb_SamplesVariable;
    private javax.swing.JLabel lbl_MarkersCriteria;
    private javax.swing.JLabel lbl_MarkersCriteriaFile;
    private javax.swing.JLabel lbl_MarkersVariable;
    private javax.swing.JLabel lbl_NewMatrixName;
    private javax.swing.JLabel lbl_ParentMatrix;
    private javax.swing.JLabel lbl_ParentMatrixName;
    private javax.swing.JLabel lbl_SamplesCriteria;
    private javax.swing.JLabel lbl_SamplesCriteriaFile;
    private javax.swing.JLabel lbl_SamplesVariable;
    private javax.swing.JPanel pnl_Footer;
    private javax.swing.JPanel pnl_MarkerZone;
    private javax.swing.JPanel pnl_NameAndDesc;
    private javax.swing.JPanel pnl_SampleZone;
    private javax.swing.JScrollPane scrl_MarkersCriteria;
    private javax.swing.JScrollPane scrl_NewMatrixDescription;
    private javax.swing.JScrollPane scrl_SamplesCriteria;
    private javax.swing.JTextArea txtA_MarkersCriteria;
    private javax.swing.JTextArea txtA_NewMatrixDescription;
    private javax.swing.JTextArea txtA_SamplesCriteria;
    private javax.swing.JTextField txt_MarkersCriteriaFile;
    private javax.swing.JTextField txt_NewMatrixName;
    private javax.swing.JTextField txt_SamplesCriteriaFile;
    // End of variables declaration//GEN-END:variables
}
