/*
 * TestIntroPanel.java
 *
 * Created on Nov 11, 2009, 6:51:46 PM
 */
package org.gwaspi.gui;

import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author fernando
 */
public class TestIntroPanel extends javax.swing.JPanel {

	/**
	 * Creates new form TestIntroPanel
	 */
	public TestIntroPanel() {
		initComponents();
		//Image logo = Toolkit.getDefaultToolkit().getImage(("/media/data/work/moapi/app/logo_white.png"));
		Image logo = pnl_Logo.createImage(50, 50);
		logo = Toolkit.getDefaultToolkit().getImage(("/media/data/work/moapi/app/logo_white.png"));
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrl_Logo = new javax.swing.JScrollPane();
        pnl_Logo = new javax.swing.JPanel();
        scroll_About = new javax.swing.JScrollPane();
        txtP_About = new javax.swing.JTextPane();
        scroll_Help = new javax.swing.JScrollPane();
        list_Help = new javax.swing.JList();
        pnl_Footer = new javax.swing.JPanel();
        scroll_Contact = new javax.swing.JScrollPane();
        txtP_Contact = new javax.swing.JTextPane();
        scroll_IBE = new javax.swing.JScrollPane();
        pnl_IBE = new javax.swing.JPanel();
        btn_exit = new javax.swing.JButton();
        btn_preferences = new javax.swing.JButton();
        btn_start = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MOAPI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("FreeSans", 0, 24))); // NOI18N

        scrl_Logo.setMaximumSize(new java.awt.Dimension(190, 151));
        scrl_Logo.setPreferredSize(new java.awt.Dimension(190, 151));

        pnl_Logo.setMaximumSize(new java.awt.Dimension(185, 150));
        pnl_Logo.setPreferredSize(new java.awt.Dimension(185, 150));

        javax.swing.GroupLayout pnl_LogoLayout = new javax.swing.GroupLayout(pnl_Logo);
        pnl_Logo.setLayout(pnl_LogoLayout);
        pnl_LogoLayout.setHorizontalGroup(
            pnl_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        pnl_LogoLayout.setVerticalGroup(
            pnl_LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 156, Short.MAX_VALUE)
        );

        scrl_Logo.setViewportView(pnl_Logo);

        scroll_About.setViewportView(txtP_About);

        list_Help.setBorder(javax.swing.BorderFactory.createTitledBorder("Help Subjects"));
        list_Help.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        list_Help.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                list_HelpMouseReleased(evt);
            }
        });
        scroll_Help.setViewportView(list_Help);

        scroll_Contact.setViewportView(txtP_Contact);

        pnl_IBE.setBackground(java.awt.Color.gray);

        javax.swing.GroupLayout pnl_IBELayout = new javax.swing.GroupLayout(pnl_IBE);
        pnl_IBE.setLayout(pnl_IBELayout);
        pnl_IBELayout.setHorizontalGroup(
            pnl_IBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );
        pnl_IBELayout.setVerticalGroup(
            pnl_IBELayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 102, Short.MAX_VALUE)
        );

        scroll_IBE.setViewportView(pnl_IBE);

        javax.swing.GroupLayout pnl_FooterLayout = new javax.swing.GroupLayout(pnl_Footer);
        pnl_Footer.setLayout(pnl_FooterLayout);
        pnl_FooterLayout.setHorizontalGroup(
            pnl_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_FooterLayout.createSequentialGroup()
                .addComponent(scroll_Contact, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_IBE, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnl_FooterLayout.setVerticalGroup(
            pnl_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_FooterLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl_FooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scroll_Contact, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scroll_IBE, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pnl_FooterLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {scroll_Contact, scroll_IBE});

        btn_exit.setText("Exit");
        btn_exit.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        btn_preferences.setText("Preferences");
        btn_preferences.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_preferencesActionPerformed(evt);
            }
        });

        btn_start.setText("Start");
        btn_start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_startActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(scroll_Help, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 748, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(scrl_Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scroll_About, javax.swing.GroupLayout.DEFAULT_SIZE, 552, Short.MAX_VALUE))
                    .addComponent(pnl_Footer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(btn_preferences)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 419, Short.MAX_VALUE)
                .addComponent(btn_exit)
                .addGap(30, 30, 30)
                .addComponent(btn_start)
                .addGap(29, 29, 29))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btn_exit, btn_preferences, btn_start});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scroll_About, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                    .addComponent(scrl_Logo, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scroll_Help, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addGap(11, 11, 11)
                .addComponent(pnl_Footer, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_start)
                    .addComponent(btn_exit)
                    .addComponent(btn_preferences))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void list_HelpMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_list_HelpMouseReleased
		// TODO add your handling code here:
    }//GEN-LAST:event_list_HelpMouseReleased

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_btn_exitActionPerformed

    private void btn_preferencesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_preferencesActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_btn_preferencesActionPerformed

    private void btn_startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_startActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_btn_startActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JButton btn_preferences;
    private javax.swing.JButton btn_start;
    private javax.swing.JList list_Help;
    private javax.swing.JPanel pnl_Footer;
    private javax.swing.JPanel pnl_IBE;
    private javax.swing.JPanel pnl_Logo;
    private javax.swing.JScrollPane scrl_Logo;
    private javax.swing.JScrollPane scroll_About;
    private javax.swing.JScrollPane scroll_Contact;
    private javax.swing.JScrollPane scroll_Help;
    private javax.swing.JScrollPane scroll_IBE;
    private javax.swing.JTextPane txtP_About;
    private javax.swing.JTextPane txtP_Contact;
    // End of variables declaration//GEN-END:variables
}
