/*
 * Copyright (C) 2013 Universitat Pompeu Fabra
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

package org.gwaspi.gui;

public class TestGWASpiExplorerPanel extends javax.swing.JPanel {

	/**
	 * Creates new form TestGWASpiExplorerPanel
	 */
	public TestGWASpiExplorerPanel() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="expanded" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splt_MOAPIPanel = new javax.swing.JSplitPane();
        scrl_Tree = new javax.swing.JScrollPane();
        scrl_Content = new javax.swing.JScrollPane();
        pnl_Content = new javax.swing.JPanel();

        scrl_Tree.setMinimumSize(new java.awt.Dimension(200, 600));
        scrl_Tree.setPreferredSize(new java.awt.Dimension(200, 600));
        splt_MOAPIPanel.setLeftComponent(scrl_Tree);

        javax.swing.GroupLayout pnl_ContentLayout = new javax.swing.GroupLayout(pnl_Content);
        pnl_Content.setLayout(pnl_ContentLayout);
        pnl_ContentLayout.setHorizontalGroup(
            pnl_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 807, Short.MAX_VALUE)
        );
        pnl_ContentLayout.setVerticalGroup(
            pnl_ContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 598, Short.MAX_VALUE)
        );

        scrl_Content.setViewportView(pnl_Content);

        splt_MOAPIPanel.setRightComponent(scrl_Content);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splt_MOAPIPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1015, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(splt_MOAPIPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnl_Content;
    private javax.swing.JScrollPane scrl_Content;
    private javax.swing.JScrollPane scrl_Tree;
    private javax.swing.JSplitPane splt_MOAPIPanel;
    // End of variables declaration//GEN-END:variables
}
